name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      id: setup_buildx
      uses: docker/setup-buildx-action@v3
    - name: Enable buildkit cache
      uses: actions/cache@v2
      with:
        path: /tmp/buildkit-cache/buildkit-state.tar
        key: ${{ runner.os }}-buildkit-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildkit-
    - name: Load buildkit state from cache
      uses: dashevo/gh-action-cache-buildkit-state@v1
      with:
        builder: buildx_buildkit_${{ steps.setup_buildx.outputs.name }}0
        cache-path: /tmp/buildkit-cache
        cache-max-size: 2g
    - name: Build and export to Docker
      uses: docker/build-push-action@v6
      with:
        load: true
        tags: sth-amis-fitting-enviroment
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - run: docker run --rm sth-amis-fitting-enviroment pytest tests/
    - run: docker run --rm sth-amis-fitting-enviroment Rscript tests/testthat.R
